# Generated by Django 5.2.13 on 2026-05-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255, verbose_name='اسم المنشأة')),
                ('activity_type', models.CharField(blank=True, max_length=255, verbose_name='نوع النشاط')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الرخصة')),
                ('cr_number', models.CharField(blank=True, max_length=100, verbose_name='رقم السجل التجاري')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('wilayat', models.CharField(blank=True, max_length=100, verbose_name='الولاية')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المسؤول')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='رقم التواصل')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('score', models.FloatField(default=0, verbose_name='النتيجة')),
                ('classification', models.CharField(blank=True, max_length=50, verbose_name='التصنيف')),
                ('is_draft', models.BooleanField(default=True, verbose_name='مسودة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='رقم البند')),
                ('text', models.TextField(verbose_name='وصف البند')),
                ('corrective_action', models.TextField(blank=True, verbose_name='الإجراء التصحيحي المقترح')),
            ],
            options={
                'verbose_name': 'بند',
                'verbose_name_plural': 'البنود',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='القسم')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('compliant', 'مستوفي'), ('non_compliant', 'غير مستوفي'), ('na', 'لا ينطبق')], default='compliant', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspections.evaluation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.item')),
            ],
            options={
                'unique_together': {('evaluation', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ResponseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evaluation_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inspections.response')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.section', verbose_name='القسم'),
        ),
    ]
