# Generated by Django 5.2.13 on 2026-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_evaluation_evaluation_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='correction_duration',
            field=models.CharField(blank=True, max_length=255, verbose_name='مدة التصحيح'),
        ),
    ]
