# Generated by Django 5.2.13 on 2026-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_alter_evaluation_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.CharField(blank=True, max_length=50, verbose_name='الأولوية'),
        ),
    ]
