# Generated by Django 5.2.13 on 2026-05-18 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_item_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sheet', models.CharField(max_length=255, verbose_name='ورقة المصدر')),
                ('source_row', models.PositiveIntegerField(verbose_name='رقم الصف')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='نوع البيان')),
                ('facility_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='اسم المنشأة')),
                ('activity_type', models.CharField(blank=True, max_length=255, verbose_name='نوع النشاط')),
                ('activity_category', models.CharField(blank=True, max_length=255, verbose_name='فئة النشاط')),
                ('governorate', models.CharField(blank=True, max_length=255, verbose_name='المحافظة')),
                ('visit_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الزيارة')),
                ('action_taken', models.TextField(blank=True, verbose_name='الإجراء المتخذ')),
                ('contact_info', models.TextField(blank=True, verbose_name='بيانات التواصل')),
                ('quality_systems', models.TextField(blank=True, verbose_name='نظم سلامة الغذاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistical_records', to='inspections.evaluation', verbose_name='التقرير المرتبط')),
            ],
            options={
                'verbose_name': 'سجل إحصائي',
                'verbose_name_plural': 'السجلات الإحصائية',
                'ordering': ['-visit_date', 'facility_name'],
                'unique_together': {('source_sheet', 'source_row')},
            },
        ),
    ]
